name: bledger
description: A decentralized platform for verifiable carbon credits
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  web3dart: ^2.6.1
  fl_chart: ^0.62.0
  google_maps_flutter: ^2.3.0
  google_maps_flutter_web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/